version: "3.6"

services:
  splunk:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - 8000:8000
    expose:
      - 8000
  nginx:
      image: nginx:latest
      container_name: nginx-with-splunk
      ports:
        - 80:80
      expose:
        - 80
      depends_on:
        - splunk
networks:
  default:
    driver: bridge
  
