version: "3.6"

services:
  splunk:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - 8000:8080
  nginx:
      image: nginx:latest
      container_name: nginx-with-splunk
      ports:
        - 80:88
      depends_on:
        - splunk
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    driver: bridge
  